README.md, config.toml
Update readme:
* how to install hugo (Debian)
* how to build website
=> README: add install/build notes

content/learn/manuals.md
added developer manuals; removed old grass ver…
=> improved manuals page

content/contribute/development.md
I fixed some typos and did some writing style editing. Please, check
=> fix typos in development page

content/learn/newcomers.md
Here's a first draft of a First Time Users page to fix #49.
I've selected some specific resources which I personally find particularly useful for newcomers, but others might have different opinions so let me know.
I think that a page on "Basic GRASS GIS concepts" might be useful which could be linked to from the newcomer page. What do you think ?
=> first draft of a First Time Users page

content/download/data.en.md
This is work in progress. I have to add links and some description and do some cleaning.
Feedback on the general direction of the way content is presented is welcome already now.
=> WIP: add content to sample data

content/download/data.en.md
=> sample data: add image, unix line endings

content/about/history.md
I did some cleaning of the history page by writing new pieces, removing others, changing some titles, adding figures, etc. Maybe some styling is then needed, like add some margin to figs would look nicer and the possibility to add caption to figures (the fig with the screenshot from the 1987 video actually contains the link to it, for example, and I would like to say so in a caption).
=> re-writing content in history page + adding some pics

content/download/data.en.md
Following up #76
@lucadelu, I could not find your review either. From your comments I understand you prefer having the screenshot where it is mentioned. I agree on your point and moved it up in this PR.
Is it along the lines you thought?
Did you have more comments?
=> sample data: move screenshot image up

content/about/credits.md
https://staging.grass.osgeo.org/about/credits/
Distingish between both addresses - fixes #94
=> Update contact information and legal address

content/learn/tryonline.md
=> TryOnline: add wiki link

content/about/community.md, content/about/history.md, content/about/history/gnu-release.md, content/about/history/releases.md, content/about/license.md, content/contribute/_index.en.md, content/contribute/donations.md, content/download/linux.en.md, content/learn/books.md, content/learn/tutorials.md, themes/grass/layouts/learn/list.html
In order to avoid the break of certificate like this:
I have changed everywhere (as possible) http --> https
In addition:
- some trailing white spaces removed
- one broken URL updated
=> http --> https

content/download/data.en.md
This PR adds two global GRASS locations to the data download section.
See also:
https://github.com/OSGeo/grass/issues/509
https://github.com/OSGeo/grass/issues/510
=> add global datasets

content/learn/tutorials.md
Fixed titles and links to portuguese tutorials
=> Update tutorials.md - fixed Portuguese tutorials 

content/news/2019_12_12_GRASS_GIS_7_8_2_released.md, content/news/2020_05_05_GRASS_GIS_7_8_3_released.md
TODO: add catchy screenshot (anyone?!)
=> news: GRASS GIS 7.8.3

content/news/2020_05_05_GRASS_GIS_7_8_3_released.md
I moved some things to the first paragraph and deleted others.
=> Edits to the 7.8.3 release news

content/about/brand.md
=> try to fix brand colors

themes/grass/assets/css/style.css
=> change color from gray light to dark for section-title color

content/contribute/development.md, themes/grass/layouts/contribute/devel.html
working on #137 
I added:
- an image
- some useful links provided in the discussion
To do:
- some fa logo are not there, probably due Font Awesome old version
=> improved devel page

content/contribute/_index.en.md, content/learn/_index.en.md
This PR tries to solve #149. I added a new subtitle in the Contribute landing page
and a sentence in the Learn landing page
=> add grass google scholar profile to contribute and learn

content/news/2020_06_28_github_actions.md
- text might still be improved, suggestions/edits welcome!
=> News: new press release about GitHub Actions

content/download/mac.en.md
=> Download-Mac: update to 7.8.3

content/download/linux.en.md
This should be changed before the release, IMHO.
=> Download-Linux: update to 7.8.3 release

themes/grass/layouts/404.html
We could also do a redirect to main page. Let me know what you prefer
=> improved 404 page #204

config.toml
I changed `config.toml` as an attempt to get a description and solve #205
=> attempt of getting a website description 

themes/grass/layouts/404.html
This is an attempt at fixing #204 by simply cleaning the 404.html template a bit.
=> clean up 404.html template

content/news/2020_09_26_GRASS_GIS_7_8_4RC1_released.md
Please suggest additions.
Screenshot welcome!
=> Draft GRASS GIS 7.8.4RC1 announcement

config.toml, static/files/sitemap.xml
renamed hugo sitemap and created new one including hugo and manual sitemaps
=> sitemap improvements #226

content/download/windows.en.md
for https://github.com/OSGeo/grass-website/issues/232
=> update OSGeo4W section with express/advanced mode hints

content/about/history/releases.md, content/download/linux.en.md, content/download/mac.en.md, content/download/windows.en.md, content/news/2020_12_21_GRASS_GIS_7_8_5_released.md
- a new screenshot would be welcome
- please review and improve as needed
=> GRASS GIS 7.8.5 release news

content/download/linux.en.md, content/download/mac.en.md, content/download/windows.en.md
This is a proposed fix for issue #237 to address broken images links and bad titles in the download section of the website.
=> Fix broken images and titles

content/download/windows.en.md, content/news/2020_12_21_GRASS_GIS_7_8_5_released.md
New 64bit wingrass binary available (see https://github.com/OSGeo/grass/issues/1218)
=> WinGRASS-7.8.5-2-Setup-x86_64 published

content/contribute/sponsoring.md, content/contribute/sponsors.md
=> Sponsoring: thanks to our sponsors with Wiki URL

content/news/2002_06_25_announce_grass500pre5.md
=> Fix date for 5.0.0pre5

content/news/2021_04_23_new_tutorials_made_by_students.md
This is a post that I'd like to publish as a GRASS news in which I highlight a couple of really nice tutorials contributed by students from a GRASS workshop I taught. Here the screenshots of how the news looks like:
The experience of asking students to develop tutorials as final exam of the GRASS workshop was really rewarding and I'd like to encourage others involved in teaching to write similar posts. I believe it's motivating for students to know their work will be recognized and shown within the software channels.
=> Post about tutorials contributed by students of a GRASS workshop

content/download/windows.en.md
Update of link to OSGeo4W, version 2. Include link to old version v1 + warning for existing users that they need a fresh install when migrating to version 2 (based on message on QGIS page)
=> Update link to osgeo4w

content/download/windows.en.md
=> Download Windows format fix and GRASS 8.0 RC2 link

content/download/windows.en.md
See https://lists.osgeo.org/pipermail/grass-user/2022-February/082861.html
=> promote WinGRASS-8.0.0-2-Setup.exe

content/download/windows.en.md, content/news/2022_01_30_GRASS_GIS_8_0_0_released.md
Fixes 
* https://github.com/OSGeo/grass/pull/2223
* missing `proj-bin`
=> Promote wingrass 8.0.0-3

content/about/history/releases.md
- 7.8.6, 7.8.7
- 8.0.0
- Creation of the GRASS GIS 8.2 release branch
=> releases: add missing release entries

content/about/history/releases.md, content/news/2022_05_12_GRASS_GIS_8_0_2_released.md
- News: release announcement added.
- history/releases.md entry about G8.0.2 added
=> News: GRASS GIS 8.0.2 released

content/learn/tutorials.md
I updated the 3 featured videos in the tutorials page, including 2 videos from foss4g 2021 and the one about grass 8 by Isaac
=> update featured videos in the tutorial page

themes/grass/assets/css/style.css
Allow outline in in buttons and links when on focus. This is good for tab navigation
=> fix: allow outline in buttons and a tags when on focus

themes/grass/layouts/contribute/devel.html
- remove old "how to contribute" guide from trac
- update link to programmers' manual
- add submitting link
=> contribute/development page: update links in the side panel

themes/grass/layouts/contribute/devel.html
=> add link to Vashek's FOSS4G 2022 workshop: write your own tool

themes/grass/layouts/_default/list.html, themes/grass/layouts/about/brand.html, themes/grass/layouts/about/community.html, themes/grass/layouts/about/credits.html, themes/grass/layouts/about/general.html, themes/grass/layouts/about/list.html, themes/grass/layouts/contribute/contribute.html, themes/grass/layouts/contribute/devel.html, themes/grass/layouts/contribute/general.html, themes/grass/layouts/contribute/list.html, themes/grass/layouts/download/addons.html, themes/grass/layouts/download/data.html, themes/grass/layouts/download/list.html, themes/grass/layouts/download/os.html, themes/grass/layouts/download/single.html, themes/grass/layouts/index.html, themes/grass/layouts/learn/books.html, themes/grass/layouts/learn/gallery.html, themes/grass/layouts/learn/list.html, themes/grass/layouts/learn/manuals.html, themes/grass/layouts/learn/overview.html, themes/grass/layouts/news/allnews.html, themes/grass/layouts/news/news.html, themes/grass/layouts/partials/banner.html
Banner at the top of the page inviting people to join Gitter chatroom
displayed in most pages/sections: news, download, learn, contribute, about, etc.
closes #329
=> Issue329: banner inviting people to join Gitter

themes/grass/layouts/index.html, themes/grass/layouts/shortcodes/donateDialog.html
hacktober modal 
changed ids for donate modal
=> Add Hacktober window for October 

themes/grass/layouts/index.html
removed hacktober dialog 
hacktober is over
=> fix: removed hacktober dialog

content/news/2023_04_08_GRASS_Community_meeting_Prague_june_2023.md
Forgot this one the other day...
=> fix support us link in community meeting news

themes/grass/layouts/events/allevents.html, themes/grass/layouts/news/allnews.html, themes/grass/layouts/partials/twitter.html
=> fix: twitter timeline

content/contribute/sponsoring.md
This is a first attempt to describe proposed sponsoring tiers and benefits that we can offer for each level. Suggestions and discussion is welcome! Also some help with table styling :-)
=> Sponsoring page: first draft with sponsoring tiers

content/news/2023_07_03_The_rmblend_experience.md
@ldesousa, I took a screenshot from r.mblend manual page and one from the community meeting wiki, but feel free to create and/or provide something different. Also, publishing date might be modified.
=> News: add news item from text contributed by @ldesousa

content/download/windows.en.md
This PR propagates new builds: 
* 8.3.1-2, see https://github.com/OSGeo/grass/issues/2603
* 7.8.8-2, see https://github.com/OSGeo/grass/issues/1965
=> Propagate new windows builds

content/news/2024_03_15_GRASS_DOI_number_at_zenodo.md
Fixes typo, see
https://github.com/OSGeo/grass-website/pull/418#pullrequestreview-1970061318
=> fix typo: GutHub -> GitHub

content/learn/tutorials.md
=> tutorials cleanup - remove non-existing links

README.md, config.toml
=> Config: change default markdown renderer to goldmark

content/about/history/releases.md
Fixes #449 although I have no idea why this works.
=> timeline: fix rendering

content/about/history/van-warren-notes.md, themes/grass/assets/css/style.css
This changes the blockquote style to look better, it will be used in tutorials when a callout note is needed.
=> blockquote: change style to use as callout node, make van warren's letter look normally

content/download/data.en.md
Addresses #454
Thanks @baharmon and @ecodiv !!
=> Data download: Fix links of global datasets

content/support/community.md
=> Community: add link to linkedin

content/about/roadmap.md, themes/grass/layouts/about/roadmap.html
This is the roadmap we discussed during the community meeting.
=> Add project roadmap

config.toml, content/about/roadmap.md
Menu entry added and sorted. Addresses https://github.com/OSGeo/grass-website/pull/458#issuecomment-2320826993 and https://github.com/OSGeo/grass-website/pull/458#issuecomment-2321309550.
=> Roadmap: Add menu entry under About us

config.toml, themes/grass/layouts/about/list.html
Update text in the About us page to match the text from index.
Update HTML description to be a shorter version of the text from index. Update keywords to include keywords from GitHub.
=> Update about and metadata texts

content/support/community.md
=> Update after moving grass-dev to Discourse

config.toml, content/learn/newcomers.md, content/learn/tutorials.md, content/support/community.md
https://www.youtube.com/@grass-gis
=> add back revived Youtube channel

config.toml
=> Fix titles

themes/grass/assets/css/style.css
Implemented the Changes as mentioned in the issue. (#496 )
=> Changed the button color to grass color (#496)

content/about/history/releases.md, content/download/linux.en.md, content/news/2025_03_02_GRASS_GIS_8_4_1_released.md, data/grass.json
~~📣 Please someone donate a screenshot! 📣~~
Update of the relevant files:
=> News item for the GRASS GIS 8.4.1 release.

config.toml, content/learn/newcomers.md, content/support/community.md, themes/grass/layouts/partials/banner.html
* Modified community page to add discourse forum
* Put mailing lists towards the end of the page
* Removed GIS on the community page as part of the edits
* Add Discourse to footer
=> Update after migration to discourse forum

themes/grass/layouts/partials/foss4g.html, themes/grass/layouts/partials/navigation.html, themes/grass/layouts/partials/osgeo.html
Added missing alt tags to index.html img elements (Issue #516)
=> SEO: Added missing alt tags to index.html img elements

config.toml
Rewritten meta description to address SEO complaints described in #513. Fixes #522.
=> Shrink meta description to avoid SEO complaining

themes/grass/layouts/support/commercial.html
See https://github.com/OSGeo/grass-website/pull/537
=> OpenGeoLabs: enhance wording

themes/grass/assets/css/style.css
Change the link colors to primary to match the new documentation (Issue #547).
=> style: changed link colors to primary

themes/grass/layouts/partials/brandDownloadIconDropdownButton.html, themes/grass/layouts/shortcodes/brandLogo.html
I added anchor links to the dropdown buttons on the brand page to prevent the page from navigating to an undefined page if a user second clicks on the button.
=> brand: Added anchor links to brand logo drop down buttons
