OSGeo/grass-website

config.toml
https://www.facebook.com/GRASSGISCommunity doesn't exist. Let's redirect to already existing Facebook group https://www.facebook.com/groups/grass
=> fix facebook link

content/about/community.md
- fix name of grass translations mailing list,
- move announcement list to the end of the table bc of less relevance for users
- change description of grass-stats since it's mostly used for GRASS-R stats interface issues
=> minor changes to table with mailing lists

content/about/community.md
Since all the links to user groups are outdated, or they just point to local OSGeo chapters, I commented out that section. See #14.
=> comment out the user groups from the community page

themes/grass/assets/css/style.css
With this change the `<a>` in a `<ul> -> <li>` should not go in a new line, @neteler @nbozon  could you please test to check if it doesn't brake anything else? (like menu or other stuff)
=> try to fix a problem in li; added new class for list without bullets

content/download/linux.en.md
Change where the link to repology is shown
=> grass gis for linux download page update

content/download/linux.en.md
issue #88 
remove duplicated download grass gis source in the download linux sub page.
download grass gis source is already in the main download menue
=> issue  #88 : remove duplicated download source

content/about/history.md, content/about/history/releases.md
I started working on fixing the list of releases (fixed date format, added GIS where missing, change word order, added some bold face here and there), but there's still quite some work to be done. Here a list:
- RC's after 7.2.0 are missing while all other RC are there
- 7.8.1 and 7.8.2 are missing (if this will be a full list, maybe we should also add them here)
- Most of version 6 and earlier releases are not in bold (we could agree here what to put in bold to make it consistent through out the list, I'd suggest only major releases)
- I did not find the figure of the roadmap
- We could split the list in sections, either decades as in History or some other criteria
- Was it called GRASS GIS before version 4?
- 1990 (Winter) GRASS 3.2 released through Internet <-- will links like this one …
=> WIP: fixing and homogenenizing style in detailed releases list

content/about/history.md
This PR creates a subsection in History page with two nice GRASS GIS anniversaries presentations and removes the one by Markus from the main text.
=> add a subsection with anniversary presentations

content/contribute/donations.md, content/download/_index.en.md, content/download/addons.en.md, content/download/data.en.md, content/download/docker.en.md, content/download/linux.en.md, content/download/mac.en.md, content/download/windows.en.md, themes/grass/layouts/download/addons.html, themes/grass/layouts/download/list.html
I created a specific layout for AddOns to avoid getting the "GRASS GIS for XX" title that makes sense for different OS but not for addons. 
The PR also fixes img sizing (I changed MD style to HTML tags to be able to control size).  
And I also fixed the logos' path for download landing page.
=> fixes download/addons and donation pages + layouts

content/learn/tryonline.md
Some minor beautification for https://staging.grass.osgeo.org/learn/tryonline/
(see also #59)
=> try online: wording and typos fixed

config.toml
As explained here: https://jdhao.github.io/2019/12/29/hugo_html_not_shown/, starting from hugo version 0.60, the HTML tags are no longer displayed by default because hugo has changed the Markdown renderer from blackfriday to goldmark.
Hence, one of the proposed solutions is adding blackfriday back in the `config.toml` file as in this PR
See #12
=> Fix HTML tags display for hugo >0.60

config.toml, content/about/brand.md, content/about/license.md
This PR
- moves `News` outside `About` and places it before `Download` in the upper menu bar,
- reorder items within `About` menu,
- adds License into `About` menu,
- beautifies `License` and, 
- moves the bibtex citation from `Brand` into `License`
addressing issues #32, #121, and partially #90.
**Remaining points to be solved:**
- side menu in License shows links to all files in the folder (as the issue solved for About in d4c0d5cabf7ef5508c7a190e5df618e98a14f94f). Can we fix it here too or maybe change the layout, @nbozon ?
- bottom of the page shows "updated + date from the header of the file" that any other page displays
=> About section clean-up

content/download/mac.en.md
Kyngchaos no longer maintains current binaries, only very old one. Reprology only seems to link to MacPorts and no binaries.
=> update Mac binary location info

content/learn/newcomers.md
I just added a couple more sentences to `First time users > Videos` section so the film camera appears surrounded by text as suggested by @lucadelu in https://github.com/OSGeo/grass-website/issues/70#issuecomment-623186769
Looks like this now:
=> fix for #70

themes/grass/assets/css/style.css, themes/grass/layouts/download/list.html
this fix the problem with smartphone but it is not working on tablets, @nbozon could you check it?
=> working on #105 GRASS GIS SVG logo too small

content/download/linux.en.md
* new stable -> current
* comment-out broken stuff (grass-daily)
* move generic links to upper part
=> clean up download linux page

content/download/windows.en.md
fix #189: OSGeo4W link on Download/Windows does not "go" anywhere.
=> fix: OSGeo4W link on Download/Windows does not "go" anywhere.

content/contribute/_index.en.md, content/download/addons.en.md, content/download/data.en.md, content/download/linux.en.md, content/download/windows.en.md, content/learn/manuals.md, content/learn/newcomers.md, content/learn/overview.md, themes/grass/layouts/partials/quicklinks.html
There should be no more need to have the URLs absolute.
Yet broken links after merging this PR might need a server-side intervention (e.g. missing redirects).
=> avoid absolute URLs to server

content/contribute/_index.en.md
This PR adds information about how to mirror the website to the Contribute landing page. This page is getting very long and so probably needs some form of refactoring sooner or later, but for now, at least the info is there.
=> add info on how to mirror website

content/about/mirrors.md, themes/grass/layouts/partials/footer.html
First attempt at adding a list of mirror sites.
Current list certainly not up to date, so needs to be corrected before release.
I added the link only on the home page. Not sure if it should go somewhere else.
The actual page is in content/about/mirrors as we have no content directly in content/ and so I didn't want to put it there. About seemed the best for now.
=> add page with mirrors sites and link on home page

themes/grass/layouts/partials/head.html
Following @mlennert's suggestion in https://github.com/OSGeo/grass-website/issues/205#issuecomment-665350781, I modified `head.html` and when inspecting the source code of home in the local build, the description is there. This should then fix #205.
=> fix description in head, suggestion by @mlennert 

content/download/data.en.md
The previous link was pointing to the NC location used in testsuite and in my opinion that was very confusing, especially because when unzipping it, there were two extra directory levels, i.e., `grassdata/tests-grassdata/nc_spm_full_v2alpha/`. I took liberty to change it to the good old full NC location as in the old site :)
I believe that the testsuite location is not (yet) what we want to provide as sample data for users. The grassdb, location and mapset concepts are already confusing for newcomers as to provide something with so many directory levels. 
Maybe, the testsuite NC location could be added as a new section at the bottom of the page or so. It could also go as a relevant link in the `Development` page.
=> fix link to download full NC location

themes/grass/layouts/download/list.html
Following suggestion in https://github.com/OSGeo/grass-website/issues/190#issuecomment-664411158, this PR moves the link to download the source code to the top of `Download` page to make it more visible while keeping the other download options visible too
=> move link to source code to the top of download landing page

content/about/license.md
The `@Manual` tag for GRASS citation was not visible within the `<pre>` and `<code>` HTML tags. This PR changes that to md code tag and now it is readable:
=> fix tex tag for grass citation

config.toml, themes/grass/layouts/partials/footer.html
Current footer contained:
"Copyright Â© 1998-2020"
With this PR it looks better:
as a bonus, it auto-increments the current year.
(Year code borrowed from https://github.com/wowchemy/wowchemy-hugo-modules/commit/5358dd00ad90fefcb50036c911382c46f38094b0 - MIT License)
=> footer: fix copyright symbol and add license

config.toml
Previous link is not a valid facebook group
=> Update facebook link

config.toml, content/contribute/sponsoring.md
Fixes #250
Deadline is today since we need to communicate the (new) URL to OSGeo, see
https://lists.osgeo.org/pipermail/projects/2021-February/000286.html
Once accepted, I'll add a redirect to the server.
=> Rename Donations page to Sponsoring

content/learn/manuals.md
fixes #255
- additionally minor wording fixes (in sync with download pages)
- stable --> current
- old stable --> old
=> learn: comment out outdated GRASS GIS 6.4 manual link

content/news/2021_08_01_g_extension_currently_not_working.md
As suggested in the mailing list, I have created a news item to inform that installing extensions is currently failing. 
Please, review :)
=> add news item about failing g.extension

content/download/docker.en.md, content/download/linux.en.md, content/download/mac.en.md, content/download/windows.en.md, content/learn/manuals.md, themes/grass/layouts/partials/quicklinks.html
* change all appearances of `grass79` to `grass80` (with one exception: https://grass.osgeo.org/sampledata/north_carolina/nc_spm_mapset_modis2015_2016_lst_grass79.zip)
* remove major version from developers manuals titles (developers manuals point always to the most recent version)
* use consistently `preview/legacy` term instead of `devel/old`
=> Change grass79 to grass80

content/learn/tutorials.md
Proposing the addition of a basic, introductory presentation about GRASS 7.8 CLI setup, and the usage of GRASS commands in the shell, R and RStudio (given at my organization, a few months ago). Comments and improvements are also welcome at https://github.com/florisvdh/presentations/tree/master/src/20210617_grass. In the [third last](https://florisvdh.github.io/presentations/20210617_grass/#72) slide a simple demo (R markdown) is linked, using vector data & rasterization.
Thanks to @veroandreo for sharing the link to this `tutorials.md` file.
=> tutorials.md: add intro tutorial on using commands

content/download/windows.en.md
Windows: remove links to outdated G8.0 preview
=> windows: remove links to outdated G8.0 preview

content/download/linux.en.md
Which provides the ability to install [GRASS GIS via ebuilds](https://packages.gentoo.org/packages/sci-geosciences/grass).
Gentoo ebuilds GRASS GIS versions:
- sci-geosciences/grass-7.8.6-r1  (stable 7.8.6 release)
- sci-geosciences/grass-8.0.0_rc2 (8.0.0 RC2 release)
- sci-geosciences/grass-9999  (8.1 dev release (git main branch))
=> content/download: add Gentoo GNU/Linux distribution

config.toml, themes/grass/layouts/download/list.html
As suggested in the mailing list, I changed the link to point tags now for a straightforward link to tarballs:
Other ideas about wording or layout preference are more than welcome :)
=> Download section: change link to tags instead of releases

themes/grass/layouts/download/list.html
After adding the extra links in the Source code row in https://grass.osgeo.org/download/, the command-like link to the github repo does not appear when the site is displayed on mobile phones or when zooming in above 170% (in my laptop screen). Hence, I thought of replacing it by a button saying `Clone me` similar to the download buttons below. It looks like this: 
and it does not disappear when zooming in a lot. On phones, I do not know. Anyway, an idea. What do you think?
PS: branch name does not really reflect the change as I originally thought it was a problem with row height (it might be indeed), but I didn't find a way to fix that. Hence, the button idea :wink:
=> Download section: replace command-like link by a button

content/learn/manuals.md
Partially addresses [#290](https://github.com/OSGeo/grass-website/issues/290)
To add development version manuals, a cronjob is yet needed AFAIU.
=> Update versions in manuals

content/download/mac.en.md
Now finally, GRASS 8 is available with the `grass` port.
This also adds the "old" port `grass7`.
=> Add MacPorts to Mac download page

themes/grass/layouts/index.html
This PR removes the text Geographic Resources Analysis Support System from the main page and replaces it by a general description about GRASS, as suggested in #298 
Before this PR: 
With this PR:
=> Add GRASS description in main page - addresses #298

content/about/community.md
- moved "GitHub Discussions for GRASS GIS" from "Mailing lists" section here for a better fit
- added "GRASS GIS on Stackexchange"
Preview:
Fixes #313
=> community: added section "Question-and-answer (Q&A) websites"

content/learn/overview.md
The last image was not displayed, seems the full website of the img is needed.
=> fix img that was not displayed in learn/overview

static/files/sitemap.xml
Apparently the use of `grass-stable/` and `grass-devel/` penalizes the new GRASS GIS 8 versions over G78 in common search engines.
Reason may be that they are only redirects which cannot be easily ranked.
This PR brings back the GRASS GIS version in the manual URLs (followup to #230) and to be considered in #318.
=> sitemap: bring SEO back through use of versions in URLs

content/download/linux.en.md
Add Fedora-COPR repo for F35 package of GRASS GIS 8.2.x.
(after merge this PR needs to be considered in #318)
=> Download: added Fedora-COPR for G82 packages

content/contribute/_index.en.md
- change to weblate and remove old instructions, replace them by a link to the glossary 
- remove GCI as it no longer exists
=> contribute page clean-up

content/learn/tutorials.md
I have reorganized the tutorials' list by creating subsections and adding date of last update between parenthesis. The latest FOSS4G tutorials were also added along with a link to Isaac's videos on GRASS 8. This is how it looks:
=> Tutorials list: Clean-up and reorganization

content/contribute/sponsoring.md
I have started updating sponsoring page. For now, some cleaning, rewording and the addition of students grants as way in which we use the money.
What about adding some quotes from Robert Dzur there too?
On the longer run, a simplified sponsoring/supporting plan as OSGeo has (https://www.osgeo.org/about/how-to-become-a-sponsor/)?
=> Update sponsoring page

config.toml
There's no icon for Gitter in the fontawesome 4.7 that we are supporting, so for now I used the comment icon:
Updating the fontawesome icon set is wip...
=> add chat icon to footer - partially address #329

themes/grass/layouts/shortcodes/donateDialog.html
changed the link in donate dialog to point directly to donate page in opencollective.com instead of the project page  (1 click less to donate)
=> donate link in donate dialog

themes/grass/assets/css/style.css, themes/grass/layouts/partials/head.html, themes/grass/layouts/partials/navigation.html
Search feature. Uses duckduck go. 
Not in focus 
When focusing the icon (for example when the user clicks on the search icon)
Issue #19 . Further discussion on implementation alternatives there
=> feature:  seach  in menu navbar

content/learn/manuals.md
List G83 manual page under learn/manuals/:
Fixes #290
=> List G83 manual page under learn/manuals/

content/download/data.en.md
Added six massively reduced Sentinel-2 scenes (SAFE format), provided by @marisn for FOSS4G 2022 course (https://github.com/veroandreo/foss4g2022_grass4rs).
While keeping the SAFE format, the Sentinel-2 scenes have been drastically reduced in size by cropping. The related metadata have been updated accordingly as much as possible to fake proper SAFE datasets.
Area: Raleigh, North Carolina.
Purpose:
This dataset is useful for teaching and unit tests.
Data file at:
https://grass.osgeo.org/sampledata/north_carolina/nc_sentinel_utm17n.zip
The ZIP files contains a README.md with explanations.
=> Sample data: added massively reduced Sentinel-2 scenes

content/about/community.md, content/about/history.md, content/learn/tryonline.md
"Trivial" PR, typos identified with `grass_main/utils/fix_typos.sh` script.
Note: Those in older press releases have been ignored on purpose.
(https://github.com/OSGeo/grass/blob/main/utils/fix_typos.sh)
=> Fix a few typos

themes/grass/layouts/404.html
Looking at recent matomo stats showed that users do not necessarily use the top menu to find stuff. Hence addition of a few core links on the "404 page not found" page.
TODO: find the appropriate "fa" icons.
With this PR it looks like this (added "manuals" and "downloads"):
=> 404 page: add a few more links

themes/grass/layouts/404.html
Aim: reduce confusion when visitors land on an outdated version announcement (problem identified with Matomo, search behaviour analysis). At least, now they know what to look for....
Shortcode from: https://github.com/OSGeo/grass-website/tree/master/themes/grass/layouts/shortcodes
Fixes #351
=> 404.html: advertise the current GRASS GIS version

content/download/linux.en.md, content/download/mac.en.md, themes/grass/assets/css/style.css
I added a button with the packaging status from Repology as was originally suggested in https://github.com/OSGeo/grass/pull/2703.
I put the button within the Linux page as I didn't find the way to filter out BSD and MacPorts, and I do not see where to put such a button in Downloads main page. This is how it looks for now:
=> download/linux: add packaging status button

content/download/mac.en.md
Add link to grasswiki with brief MacPorts instructions for installing/compiling GRASS.
=> macOS: add link to MacPorts instructions

.gitignore
To help out newcomers when running `hugo server` locally, this prevents showing that this is a new file that would be added to the repository.
It's not much, but it was a common commit I was doing when exploring how to make contributing easier in the repo.
=> Add .hugo_build.lock and hugo.exe file to .gitignore

content/contribute/sponsoring.md, themes/grass/layouts/shortcodes/donateDialog.html
We have created different sponsor tiers in Opencollective and hence, this PR changes the donation links to https://opencollective.com/osgeo/projects/grass/contribute so potential donor can choose from them
=> Donation links: Point to different contribution options page

README.md, content/events/FOSS4G_2022.md, content/events/FOSS4G_2023.md
- add FOSS4G 2023
- also add missing FOSS4G 2022 (for posterity)
- clarify date format in README.md
Screenshot:
=> News: add FOSS4G 2023 event

themes/grass/layouts/partials/foss4g.html
FOSS4G widget points to year 2022
=> fix FOSS4G link -> 2023

content/about/license.md, themes/grass/layouts/index.html
I have added the DOI badge for 8.2.1 in the Licence page and also included the doi in the bibtex string. Would be nice to somehow automate it though
=> Add DOI badge

themes/grass/assets/css/style.css, themes/grass/layouts/_default/list.html, themes/grass/layouts/_default/single.html, themes/grass/layouts/about/brand.html, themes/grass/layouts/about/community.html, themes/grass/layouts/about/credits.html, themes/grass/layouts/about/general.html, themes/grass/layouts/about/list.html, themes/grass/layouts/about/theme.html, themes/grass/layouts/about/timeline.html, themes/grass/layouts/contribute/contribute.html, themes/grass/layouts/contribute/devel.html, themes/grass/layouts/contribute/general.html, themes/grass/layouts/contribute/list.html, themes/grass/layouts/download/addons.html, themes/grass/layouts/download/data.html, themes/grass/layouts/download/list.html, themes/grass/layouts/download/os.html, themes/grass/layouts/download/single.html, themes/grass/layouts/events/allevents.html, themes/grass/layouts/events/event.html, themes/grass/layouts/index.html, themes/grass/layouts/learn/books.html, themes/grass/layouts/learn/gallery.html, themes/grass/layouts/learn/list.html, themes/grass/layouts/learn/manuals.html, themes/grass/layouts/learn/overview.html, themes/grass/layouts/news/allnews.html, themes/grass/layouts/news/news.html
**Expected behavior of banner and nav bar element (due fixed position are still visible) during page scrolling**:
Example:
**A. home page URL**
1. Desktop layout
2. Mobile layout 
**B. about/community/ URL**
1. Desktop layout
2. Mobile layout
=> Set fixed position of banner and navbar element during page scrolling

themes/grass/layouts/events/allevents.html, themes/grass/layouts/news/allnews.html, themes/grass/layouts/partials/mastodon.html
This PR ~~replaces~~ adds on top of the broken X feed our mastodon news feed from https://fosstodon.org/@grassgis .
Code kindly crafted with https://www.mastofeed.com/
Screenshot:
May replace X (formerly Twitter) since their feed is broken if not login'ed to X.
Fixes #380
=> news: mastodon news feed support added

content/download/mac.en.md, content/news/2023_06_24_GRASS_GIS_8_3_released.md, content/news/2023_08_06_GRASS_GIS_7_8_8_released.md
Old:
- http://grassmac.wikidot.com/downloads
New:
- https://cmbarton.github.io/grass-mac/
=> download: GRASS GIS on Mac moved to new site

data/grass.json
Required after release of
https://grass.osgeo.org/news/2023_08_06_grass_gis_7_8_8_released/
=> data: update 'legacy_version' to GRASS GIS 7.8.8

content/download/docker.en.md
"releasebranch" was mispelled as "relesebranch"
Fixed #386
=> docker: fix typo in branch name

content/news/2023_08_27_GRASS_GIS_docker_organization.md
GRASS GIS docker images moved from mundialis to OSGeo dockerhub organization.
Co-Authored-By: @mmacata
=> news: GRASS GIS docker images moved to OSGeo org

content/about/theme.md
The original web site is no longer, hence referring to content of https://web.archive.org/web/20210613053834/https://mapsk.in/#software
(discovered by @cmbarton)
=> theme: mapsk.in site gone, replaced by web.archive.org

content/about/mirrors.md, content/contribute/_index.en.md, themes/grass/layouts/contribute/list.html
Changes include:
* change title
* added sponsoring
* removed website mirror (moved instructions to https://grass.osgeo.org/about/mirrors/)
* small rewrites to keep information concise and relevant
* moved student grants and gsoc to Contribute to GRASS GIS core
=> Improve Contribute page

config.toml, content/about/citation.md, content/about/license.md, content/contribute/_index.en.md
Citation moved from About-License to separate page About-Citation to be more prominent (and removed it from License page).
I added Google scholar profile to that page. I just updated the citation to 2023 and 8.3 version.
I included a google form for people to add their publications, it's linked to grass.devteam@gmail.com.
=> Citation: moved to separate page and add google scholar

content/download/mac.en.md
Update URL to Repology badge for MacPorts version (https://grass.osgeo.org/download/mac/).
It is now broken:
=> Update Repology badge URL for MacPorts

content/learn/tutorials.md
also filter only GRASS GIS tutorials in the link, instead of showing all tutorials
=> manuals: fix broken link for ecodiv manuals

content/download/windows.en.md
This PR updates Windows installers to:
* https://grass.osgeo.org/grass83/binary/mswindows/native/WinGRASS-8.3.1-3-Setup.exe
* https://grass.osgeo.org/grass78/binary/mswindows/native/x86_64/WinGRASS-7.8.8-3-Setup-x86_64.exe
Unfortunaly the installers introduced by #410 are broken, see https://github.com/OSGeo/grass/pull/3419 for details.
=> Update Windows installer binary version

content/download/windows.en.md
The [website ](https://grass.osgeo.org/download/windows/#standalone-installers)points to a [standalone installer](https://grass.osgeo.org/grass83/binary/mswindows/native/WinGRASS-8.3.2-3-Setup.exe) for Windows which doesn't exist.
I thought last week it might be a temporary glitch (i.e. the website being updated while a new version was being uploaded) but now it is clear it wasn't very temporary...
I guess there was just an oversight and the link wasn't updated when the release was made.  This should fix it.
=> Fix link to standalone Windows installer

content/news/2024_03_18_GRASS_Community_meeting_Prague_2024.md, themes/grass/assets/css/style.css
News post for the 2024 edition of the community meeting. Content is mostly copied from 2023's news.
=> news: post about the community meeting in Prague, 2024 edition

.github/workflows/hugo.yml
This PR is made so that the new website in progress can be viewed when PRs made to branch "preview" are merged. This way, "master", that is currently live on [grass.osgeo.org](https://grass.osgeo.org), isn’t impacted, and the work can be done in multiple merged PRs.
It can also help with previewing the changes of configuration needed for upgrading Hugo’s version. Since it is there, it can be used by forks too, if you have the GitHub pages enabled in your fork.
=> Deploy preview website with GitHub pages (from preview branch)

themes/grass/layouts/partials/quicklinks.html
Font awesome icon name fixed, now it displays a clock.
=> learn/manuals: quick link to temporal was missing icon

content/about/history.md
Add CERL video with <iframe> instead of a picture. Now it's clear that it is a video and it can be played in place. Caption and DOI added as well. 
Addresses #433
=> History: Embed CERL video instead of picture

content/about/history/releases.md
Add entry for creation of the GRASS GIS 8.4 release branch with commit hash.
(will show up in https://grass.osgeo.org/about/history/releases/)
=> releases.md: add creation of new G84 release branch

themes/grass/layouts/contribute/devel.html
So far there doesn't seem to be a hint on the website how to compile GRASS GIS.
Added URL to related ["Compile and install" Wiki page](https://grasswiki.osgeo.org/wiki/Compile_and_Install) now under Quick links (box) next to "Source code":
=> Development: add URL to "Compile and install" under Quick links

content/news/2024_07_27_GRASS_GIS_8_4_0_released.md
Add Archlinux based distribution link.
Also available as an autobuild for arch4edu repository : https://github.com/arch4edu/arch4edu/
=> Add Archlinux based distribution link in Readme 8.4.0

content/news/2023_12_19_annual_report.md
Building pages locally is failing with hugo v0.128.2:
```
Error: error building site: render: failed to render pages: render of "page" failed: "/home/martin/src/grass-website/themes/grass/layouts/news/news.html:26:10": execute of template failed: template: news/news.html:26:10: executing "news/news.html" at <.Content>: error calling Content: "/home/martin/src/grass-website/content/news/2023_12_19_annual_report.md:1:1": execute of template failed: template: _default/_markup/render-link.html:1:14: executing "_default/_markup/render-link.html" at <urls.Parse>: error calling Parse: parse "(https://cnr.ncsu.edu/geospatial/news/2023/04/26/spring-2023-geospatial-forum-rewind/)": first path segment in URL cannot contain colon
```
This PR fixes two syntax errors. Now it builts successfully:
```
| …
```
=> Fix markdown syntax typos

content/news/2024_07_27_GRASS_GIS_8_4_0_released.md
This PR:
- modify UbuntuGIS link to show grass packages only
- add Nix link
=> GRASS 8.4.0 news: update Ubuntu link + add Nix

themes/grass/assets/css/style.css
The headings currently have different colors and margins are inconsistent. This is an attempt to standardize it. 
For page title there is special class `page-title` that can be used to highlight it (it's green), I didn't modify it.
Here is an example (disregard the text):
=> Standardize heading style and margins

content/learn/overview.md, content/learn/tutorials.md
When we archived old GUI imgs, some links got broken. Here, I replaced those of the learn/overview page. I'll check other pages and fix as well. Wording of the text is material for a different PR and discussion ;-)
=> Overview: replace imgs that were archived

themes/grass/layouts/index.html
This keeps the same idea of fully defining the software right on the main page, but makes it a bit shorter and more aligned with (one) engine (as opposed to containing a series of engines).
| Before | After |
| --- | --- |
|![Screenshot from 2024-08-29 15-42-34](https://github.com/user-attachments/assets/58d9a21a-87a2-4218-9a6c-d4012426925c) | ![Screenshot from 2024-08-29 15-41-59](https://github.com/user-attachments/assets/e8eef4c3-97f5-4f72-aea4-14c72938890c) |
=> Shorten intro text on the main page

themes/grass/assets/css/style.css, themes/grass/layouts/index.html
The banner now takes less space by cutting space at the top and bottom.
| Before | After |
| --- | --- |
| ![Screenshot from 2024-08-29 16-13-21](https://github.com/user-attachments/assets/79c2c561-65a4-4791-b7e4-a4196036d177) | ![Screenshot from 2024-08-29 16-13-04](https://github.com/user-attachments/assets/350129ea-a7a3-4e46-a15f-02ee25b8a297) |
=> Take less vertical space in the banner

config.toml, content/support/community.md
I addressed some warnings in compilation and that fixed the display of copyright info. Fixes #465.
=> footer: fix copyright display

themes/grass/layouts/contribute/devel.html
Update "Development Quick links" to not point to trac but to GitHub.
Fixes #472
https://grass.osgeo.org/contribute/development/
=> Update Development Quick links URLs

content/contribute/sponsoring.md, content/learn/overview.md, themes/grass/layouts/partials/osgeo.html
Use project of OSGeo rather than founding member becuase the terminology is OSGeo project and that's also what needs to be highlighted.
The founding member has historical significance so it is kept in the history page, but removed from anywhere else.
=> Replace 'founding member' by 'project of OSGeo'

themes/grass/assets/js/contributor_ad.js, themes/grass/layouts/partials/footer.html
I've added code to display the follwing message to potential contributors who are looking at the websites console logs.
```bash
__________  ___   __________    _______________
/ ____/ __ \/   | / ___/ ___/   / ____/  _/ ___/
/ / __/ /_/ / /| | \__ \\_  \   / / __ / / \__ \
/ /_/ / _, _/ ___ |___/ /__/ /  / /_/ // / ___/ /
\____/_/ |_/_/  |_/____/____/   \____/___//____/
Curious about GRASS GIS? Consider contributing or join our mentoring program!
https://grass.osgeo.org/contribute/development/
```
=> Added contributor recruitment message to console

themes/grass/layouts/_default/home.sitemap.xml
So far https://grass.osgeo.org/sitemap.xml showed the versioned manual pages which is unhelpful in terms of consolidating search engine results for manuals. In the past months we were penalized by "duplicate content".
For an overview, see https://github.com/OSGeo/grass/issues/4579
For efforts to address this situation, see
- https://github.com/OSGeo/grass-addons/pull/1168
- https://github.com/OSGeo/grass-addons/pull/1241
This PR changes the URL in `sitemap.xml` from versioned manual URLs to grass-stable/grass-devel in order to complete the other PRs.
This also makes the manual "landing" independent from the actual version.
=> sitemap.xml: switch from versioned manual URLs to stable/devel

content/download/windows.en.md
Fix: add `v1/` to path (source dir is nowadays: https://download.osgeo.org/osgeo4w/v1/).
=> Windows: fix legacy OSGeo4W download URLs

config.toml, themes/grass/layouts/partials/footer.html
Fixes #498
Added LinkedIn logo to the footer between gitter and fosstodon.
Made changes to config.toml
=> Added linkdin logo to footer 

themes/grass/layouts/partials/head.html
@cwhite911 could check if this makes sense or it needs to be different? Related to #513 
Scope: avoid that mirror sites take a higher search engine ranking by pointing users to the main site.
=> Add canonical URL

config.toml, themes/grass/layouts/partials/footer.html
I've added an `aria-label` attribute to each of the social links in the footer to address Issue https://github.com/OSGeo/grass-website/issues/518.
=> SEO: Added aria-labels to social links

content/about/mirrors.md
- added IBIBLIO mirror (USA)
- removed Indian mirror page as it is nowadays just an `iframe` of the original site
- removed old commented-out server entries
- update of http to https where needed
- cleanup "Tier 1" entries, add missing mirroring institutions
- replace "grass-web(at)lists.osgeo.org" with https://grass.osgeo.org/support/
=> mirrors: cleanup of mirrors

content/contribute/_index.en.md, themes/grass/layouts/contribute/devel.html
I replaced the remaining occurrences of the grass-dev mailing list with the new Discourse GRASS dev community.
=> Replace grass-dev mailing list with GRASS Dev on Discourse

content/about/brand.md, content/about/history.md
- expand GRASS acronym (at least in one place on the website)
- remove GIS from "GRASS GIS" as per PSC decision
=> history: expand GRASS acronym

config.toml
Addresses #541. The submenu points to weblate site directly.
=> Add translate submenu under contribute

content/news/2025_03_03_GRASS_Developer_Summit_2025.md, content/news/2025_05_27_GRASS_Dev_Summit_Report.md, themes/grass/layouts/index.html
The titles and links for the developer summit look are unclear. The new titles, link, and text show better that we are after the summit and point better to the report news post.
=> news: Highlight we are after the summit

content/about/mirrors.md
TENET (South African mirror host) contacted me to announce the deactivation upcoming this month.
This PR removes the entry accordingly.
A big thank-you to TENET for their long term service!
=> mirror sites: remove deactivated South African mirror
